CREATE TABLE users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      username VARCHAR(255) NOT NULL,
      name VARCHAR(255) NULL,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL,
      authToken VARCHAR(255),
      avatar VARCHAR(255) NULL,
      created_at timestamp DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      name VARCHAR(255) NULL
);

CREATE TABLE categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      title VARCHAR(255) NULL,
      owner INTEGER NOT NULL
);

CREATE TABLE groups (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      title VARCHAR(255) NULL,
      owner INTEGER NOT NULL
);

CREATE TABLE timers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      title VARCHAR(255) NULL,
      start_at timestamp DEFAULT CURRENT_TIMESTAMP,
      end_at timestamp NULL,
      created_at timestamp DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      user_id INTEGER NOT NULL,
      role_id INTEGER NOT NULL
);

CREATE TABLE user_timers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      user_id INTEGER NOT NULL,
      timer_id INTEGER NOT NULL
);

CREATE TABLE timers_categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      category_id INTEGER NOT NULL,
      timer_id INTEGER NOT NULL
);

CREATE TABLE users_groups (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
      user_id INTEGER NOT NULL,
      group_id INTEGER NOT NULL
);

INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');

INSERT INTO users(username, name, email, password) VALUES('testuser', 'Test User', 'test@test.ee', '$2a$10$bAtlktEzHZAOjSTi2X53uOpI7JyjlZ8PPYgwn5IIdaX7mxP96d9Uq');
INSERT INTO user_roles(user_id, role_id) VALUES(1, 1);

INSERT INTO timers(title, start_at, end_at) VALUES('1 Timer', '2018-08-31 18:17:56', '2018-08-31 21:17:56');
INSERT INTO timers(title, start_at, end_at) VALUES('2 Timer', '2017-03-16 01:38:45', '2017-03-16 06:38:45');
INSERT INTO timers(title, start_at, end_at) VALUES('3 Timer', '2017-09-21 19:45:36', '2017-09-21 20:45:36');
INSERT INTO timers(title, start_at, end_at) VALUES('4 Timer', '2018-01-16 14:00:14', '2018-01-16 18:00:14');
INSERT INTO timers(title, start_at, end_at) VALUES('5 Timer', '2018-11-22 09:31:02', '2018-11-22 19:31:02');
INSERT INTO timers(title, start_at, end_at) VALUES('6 Timer', '2018-08-27 18:37:50', '2018-08-27 21:37:50');
INSERT INTO timers(title, start_at, end_at) VALUES('7 Timer', '2018-10-25 03:35:26', '2018-10-25 23:35:26');
INSERT INTO timers(title, start_at, end_at) VALUES('8 Timer', '2018-12-08 13:05:17', '2018-12-08 15:05:17');
INSERT INTO timers(title, start_at, end_at) VALUES('9 Timer', '2018-04-29 19:12:35', '2018-04-29 22:12:35');
INSERT INTO timers(title, start_at, end_at) VALUES('10 Timer', '2018-10-16 03:05:00', '2018-10-16 05:05:00');
INSERT INTO timers(title, start_at, end_at) VALUES('11 Timer', '2017-08-22 17:33:16', '2017-08-22 19:33:16');
INSERT INTO timers(title, start_at, end_at) VALUES('12 Timer', '2017-07-07 14:36:42', '2017-07-07 17:36:42');
INSERT INTO timers(title, start_at, end_at) VALUES('13 Timer', '2018-01-08 20:09:15', '2018-01-08 22:09:15');
INSERT INTO timers(title, start_at, end_at) VALUES('14 Timer', '2017-02-09 04:03:38', '2017-02-09 07:03:38');
INSERT INTO timers(title, start_at, end_at) VALUES('15 Timer', '2018-02-23 00:53:09', '2018-02-23 06:53:09');
INSERT INTO timers(title, start_at, end_at) VALUES('16 Timer', '2018-10-15 02:40:33', '2018-10-15 03:40:33');
INSERT INTO timers(title, start_at, end_at) VALUES('17 Timer', '2017-09-03 01:29:14', '2017-09-03 08:29:14');
INSERT INTO timers(title, start_at, end_at) VALUES('18 Timer', '2017-09-28 13:09:35', '2017-09-28 15:09:35');
INSERT INTO timers(title, start_at, end_at) VALUES('19 Timer', '2018-10-08 18:26:41', '2018-10-08 21:26:41');
INSERT INTO timers(title, start_at, end_at) VALUES('20 Timer', '2017-09-04 14:50:56', '2017-09-04 16:50:56');
INSERT INTO timers(title, start_at, end_at) VALUES('21 Timer', '2018-10-18 14:24:42', '2018-10-18 18:24:42');
INSERT INTO timers(title, start_at, end_at) VALUES('22 Timer', '2017-01-14 06:12:07', '2017-01-14 09:12:07');
INSERT INTO timers(title, start_at, end_at) VALUES('23 Timer', '2017-05-17 19:23:27', '2017-05-17 22:23:27');
INSERT INTO timers(title, start_at, end_at) VALUES('24 Timer', '2018-08-17 02:57:57', '2018-08-17 13:57:57');
INSERT INTO timers(title, start_at, end_at) VALUES('25 Timer', '2018-04-20 14:28:51', '2018-04-20 18:28:51');
INSERT INTO timers(title, start_at, end_at) VALUES('26 Timer', '2017-12-06 10:26:07', '2017-12-06 13:26:07');
INSERT INTO timers(title, start_at, end_at) VALUES('27 Timer', '2018-09-04 11:17:25', '2018-09-04 12:17:25');
INSERT INTO timers(title, start_at, end_at) VALUES('28 Timer', '2017-11-18 09:43:46', '2017-11-18 15:43:46');
INSERT INTO timers(title, start_at, end_at) VALUES('29 Timer', '2018-08-20 00:24:10', '2018-08-20 16:24:10');
INSERT INTO timers(title, start_at, end_at) VALUES('30 Timer', '2018-02-28 09:55:29', '2018-02-28 12:55:29');
INSERT INTO timers(title, start_at, end_at) VALUES('31 Timer', '2019-03-20 02:07:05', '2019-03-20 04:07:05');
INSERT INTO timers(title, start_at, end_at) VALUES('32 Timer', '2019-04-11 02:19:53', '2019-04-11 06:19:53');
INSERT INTO timers(title, start_at, end_at) VALUES('33 Timer', '2019-04-07 21:46:11', '2019-04-07 23:46:11');
INSERT INTO timers(title, start_at, end_at) VALUES('34 Timer', '2019-03-28 17:53:26', '2019-03-28 18:53:26');
INSERT INTO timers(title, start_at, end_at) VALUES('35 Timer', '2019-03-17 15:24:20', '2019-03-17 19:24:20');
INSERT INTO timers(title, start_at, end_at) VALUES('36 Timer', '2019-02-11 06:54:04', '2019-02-11 14:54:04');
INSERT INTO timers(title, start_at, end_at) VALUES('37 Timer', '2019-01-14 20:59:27', '2019-01-14 22:59:27');
INSERT INTO timers(title, start_at, end_at) VALUES('38 Timer', '2019-01-11 18:12:03', '2019-01-11 21:12:03');
INSERT INTO timers(title, start_at, end_at) VALUES('39 Timer', '2019-04-24 18:46:35', '2019-04-24 20:46:35');
INSERT INTO timers(title, start_at, end_at) VALUES('40 Timer', '2019-03-04 14:02:00', '2019-03-04 18:02:00');
INSERT INTO timers(title, start_at, end_at) VALUES('41 Timer', '2019-05-06 12:05:44', '2019-05-06 13:05:44');
INSERT INTO timers(title, start_at, end_at) VALUES('42 Timer', '2019-02-22 12:18:04', '2019-02-22 19:18:04');
INSERT INTO timers(title, start_at, end_at) VALUES('43 Timer', '2019-02-28 00:06:59', '2019-02-28 05:06:59');
INSERT INTO timers(title, start_at, end_at) VALUES('44 Timer', '2019-05-08 03:57:03', '2019-05-08 07:57:03');
INSERT INTO timers(title, start_at, end_at) VALUES('45 Timer', '2019-01-16 16:25:29', '2019-01-16 19:25:29');
INSERT INTO timers(title, start_at, end_at) VALUES('46 Timer', '2019-03-25 13:43:16', '2019-03-25 22:43:16');
INSERT INTO timers(title, start_at, end_at) VALUES('47 Timer', '2019-04-17 08:58:21', '2019-04-17 16:58:21');
INSERT INTO timers(title, start_at, end_at) VALUES('48 Timer', '2019-02-25 01:58:43', '2019-02-25 09:58:43');
INSERT INTO timers(title, start_at, end_at) VALUES('49 Timer', '2019-05-07 18:12:14', '2019-05-07 19:12:14');
INSERT INTO timers(title, start_at, end_at) VALUES('50 Timer', '2019-05-06 20:14:47', '2019-05-06 22:14:47');
INSERT INTO timers(title, start_at, end_at) VALUES('51 Timer', '2019-04-13 20:40:18', '2019-04-13 21:40:18');
INSERT INTO timers(title, start_at, end_at) VALUES('52 Timer', '2019-04-02 23:22:55', '2019-04-02 23:48:55');
INSERT INTO timers(title, start_at, end_at) VALUES('53 Timer', '2019-04-19 02:49:08', '2019-04-19 06:49:08');
INSERT INTO timers(title, start_at, end_at) VALUES('54 Timer', '2019-04-17 10:48:24', '2019-04-17 13:48:24');
INSERT INTO timers(title, start_at, end_at) VALUES('55 Timer', '2019-04-28 21:03:23', '2019-04-28 23:03:23');
INSERT INTO timers(title, start_at, end_at) VALUES('56 Timer', '2019-04-09 21:32:18', '2019-04-09 22:32:18');
INSERT INTO timers(title, start_at, end_at) VALUES('57 Timer', '2019-04-30 11:11:13', '2019-04-30 14:11:13');
INSERT INTO timers(title, start_at, end_at) VALUES('58 Timer', '2019-04-14 10:45:38', '2019-04-14 18:45:38');
INSERT INTO timers(title, start_at, end_at) VALUES('59 Timer', '2019-04-27 06:06:05', '2019-04-27 16:06:05');
INSERT INTO timers(title, start_at, end_at) VALUES('60 Timer', '2019-04-24 22:29:15', '2019-04-24 23:29:15');

INSERT INTO user_timers(user_id, timer_id) VALUES(1, 1);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 2);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 3);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 4);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 5);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 6);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 7);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 8);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 9);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 10);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 11);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 12);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 13);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 14);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 15);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 16);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 17);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 18);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 19);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 20);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 21);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 22);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 23);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 24);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 25);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 26);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 27);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 28);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 29);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 30);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 31);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 32);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 33);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 34);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 35);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 36);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 37);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 38);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 39);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 40);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 41);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 42);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 43);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 44);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 45);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 46);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 47);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 48);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 49);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 50);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 51);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 52);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 53);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 54);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 55);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 56);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 57);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 58);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 59);
INSERT INTO user_timers(user_id, timer_id) VALUES(1, 60);

INSERT INTO categories(title, owner) VALUES('Bug fix', 1);
INSERT INTO categories(title, owner) VALUES('Improvement', 1);
INSERT INTO categories(title, owner) VALUES('Testing', 1);
INSERT INTO categories(title, owner) VALUES('New technologies', 1);

INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 58);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 57);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 56);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 46);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 42);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 34);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 18);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 40);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 21);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 32);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 22);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 16);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 1);
INSERT INTO timers_categories(category_id, timer_id) VALUES(1, 2);

INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 59);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 60);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 3);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 4);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 5);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 6);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 48);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 51);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 45);
INSERT INTO timers_categories(category_id, timer_id) VALUES(2, 43);

INSERT INTO timers_categories(category_id, timer_id) VALUES(3, 47);
INSERT INTO timers_categories(category_id, timer_id) VALUES(3, 44);
INSERT INTO timers_categories(category_id, timer_id) VALUES(3, 54);
INSERT INTO timers_categories(category_id, timer_id) VALUES(3, 17);
INSERT INTO timers_categories(category_id, timer_id) VALUES(3, 35);

INSERT INTO timers_categories(category_id, timer_id) VALUES(4, 53);
INSERT INTO timers_categories(category_id, timer_id) VALUES(4, 50);
INSERT INTO timers_categories(category_id, timer_id) VALUES(4, 39);
INSERT INTO timers_categories(category_id, timer_id) VALUES(4, 38);
INSERT INTO timers_categories(category_id, timer_id) VALUES(4, 37);


